### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Desiki-high** [kevinsu20/Vitis-ai-zcu104-yolov5#4]
想请问下，量化过程中 calib 和 test 需要使用不同的数据集吗？

**Comment by kevinsu20** [comment]
不好意思，距离研一做这个项目已经两年，不太记得了，我后续没有继续再做，所以你自己研究一下官方手册吧 :)

**Comment by Desiki-high** [comment]
好的，我已经解决了，应该是不需要使用不同的数据集的。
